services:
  - type: web
    name: mirai-lect-27-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node app.js
    envVars:
      - key: NODE_VERSION
        value: 20
